name: Extras
main: pw.kaboom.extras.Main
description: Plugin that adds extra functionality to the Kaboom.pw server.
depend: [WorldEdit]
api-version: 1.13
version: master

commands:
   clearchat:
      aliases: cc
      description: Clears messages from the chat
      permission: extras.clearchat
   console:
      description: Broadcasts a message as the console
      permission: extras.console
   destroyentities:
      description: Destroys all entities in every world
      permission: extras.destroyentities
   discord:
      description: Join the Kaboom.pw Discord server
      permission: extras.discord
   enchantall:
      description: Adds every enchantment to a held item
      permission: extras.enchantall
   end:
      description: Moves you to the End
      permission: extras.end
   jumpscare:
      aliases: scare
      description: Scares a player
      permission: extras.jumpscare
   nether:
      description: Moves you to the Nether
      permission: extras.nether
   overworld:
      description: Moves you to the Overworld
      permission: extras.overworld
   prefix:
      aliases: [rank, tag]
      description: Changes your tag
      permission: extras.prefix
   spawn:
      description: Teleports you to spawn
      permission: extras.spawn
   tellraw:
      description: Broadcasts raw text to the server
      permission: extras.tellraw
   unloadchunks:
      description: Unloads all unused chunks
      permission: extras.unloadchunks
   username:
      description: Changes your username on the server
      permission: extras.username
   vote:
      description: Shows vote links for the server
      permission: extras.vote
