name: Extras
main: pw.kaboom.extras.Main
description: Plugin that adds extra functionality to the Kaboom.pw server.
version: master

commands:
   clearchat:
      aliases: cc
      description: Clears messages from the chat
      permission: extras.clearchat
   console:
      description: Broadcasts a message as the console
      permission: extras.console
   destroyentities:
      description: Destroys all entities in every world
      permission: extras.destroyentities
   enchantall:
      description: Adds every enchantment to a held item
      permission: extras.enchantall
   jumpscare:
      aliases: scare
      description: Scares a player
      permission: extras.jumpscare
   prefix:
      aliases: [rank, tag]
      description: Changes your tag
      permission: extras.prefix
   skin:
      description: Changes your skin
      permission: extras.skin
   spawn:
      description: Teleports you to spawn
      permission: extras.spawn
   tellraw:
      description: Broadcasts raw text to the server
      permission: extras.tellraw
   unloadchunks:
      description: Unloads all unused chunks
      permission: extras.unloadchunks
   username:
      description: Changes your username on the server
      permission: extras.username
