name: Extras
main: pw.kaboom.extras.Main
description: Plugin that adds extra functionality to the Kaboom.pw server.
version: ${project.version}

commands:
   clearchat:
      aliases: cc
      description: Clears messages from the chat
      permission: extras.clearchat
   console:
      description: Broadcasts a message as the console
      permission: extras.console
   discord:
      description: Join the Kaboom.pw Discord server
      permission: extras.discord
   end:
      description: Moves your player to the End
      permission: extras.end
   flatlands:
      description: Moves your player to the Flatlands
      permission: extras.flatlands
   hub:
      description: Moves your player to the Hub
      permission: extras.hub
   nether:
      description: Moves your player to the Nether
      permission: extras.nether
   overworld:
      description: Moves your player to the Overworld
      permission: extras.overworld
   prefix:
      aliases: [rank, tag]
      description: Changes your tag
      permission: extras.prefix
   spawn:
      description: Teleports you to spawn
      permission: extras.spawn
   tellraw:
      description: Broadcasts raw text to the server
      permission: extras.tellraw
   vote:
      description: Shows vote links for the server
      permission: extras.vote
